=== Vamshimandala29/wtlab/week5/books_validate.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="bookshelf">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" name="book">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="title" type="xs:string" />
              <xs:element name="author" type="xs:string" />
              <xs:element name="isbn" type="xs:string" />
              <xs:element name="publisher" type="xs:string" />
              <xs:element name="edition" type="xs:string" />
              <xs:element name="price" type="xs:int" />
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== Vamshimandala29/wtlab/week5/bookshelf_xml.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="books_style.xsl"?>
<bookshelf
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="books_validate.xsd">
	
	<book>
		<title>Baahubali 2 - The Conclusion</title>
		<author>S.S Rajamouli</author>
		<isbn>9586413589745</isbn>
		<publisher>Arka Mediaworks</publisher>
		<edition>3rd</edition>
		<price>2000</price>
	</book>
	
	<book>
		<title>KGF 2</title>
		<author>Prashant Neel</author>
		<isbn>9856741235694</isbn>
		<publisher>Sandalwood</publisher>
		<edition>9th</edition>
		<price>7000</price>
	</book>
	
	<book>
		<title>The Hitchhiker's Guide to the Galaxy</title>
		<author>Douglas Adams</author>
		<isbn>9780307417138</isbn>
		<publisher>Random House Publishing Group</publisher>
		<edition>4th</edition>
		<price>2000</price>
	</book>
	
	<book>
		<title>Charlie and the Chocolate Factory</title>
		<author>Roald Dahl</author>
		<isbn>9780141960616</isbn>
		<publisher>Penguin</publisher>
		<edition>5th</edition>
		<price>3000</price>
	</book>
	
	<book>
		<title>Python</title>
		<author>Guido Van Rossum</author>
		<isbn>9780141378480</isbn>
		<publisher>9780141960616</publisher>
		<edition>4th</edition>
		<price>2000</price>
	</book>
		
</bookshelf>
